### ISSUE TITLE
Rain (actual) is triggered a lot without actual rain

### ISSUE THREAD

**Issue by shairevivo** [GuyKh/ims-custom-component#7] opened 2023-02-14 09:33 UTC
I added the integration to home assistant and it seems like the rain alert is not reliable.

**Comment by vadimnazaroff** [comment] 2023-02-14 12:46
Observed similar behavior, state is "rain" while actually there is no rain

**Comment by GuyKh** [comment] 2023-03-07 11:25
I think it's a limitation / by design.

The API is calling [https://ims.gov.il/en/now_analysis](https://ims.gov.il/en/now_analysis)  in an interval specified by you (default = 60 mins).
So this is just a reflection by IMS data.

🤷🏻

**Comment by GuyKh** [comment] 2024-11-12 07:47
I suggest maybe that you'll create a template (binary) sensor based on `rain` sensor, with your custom preferences.
Closing the issue for now.

**Closed as completed by GuyKh** 2024-11-12 07:47 UTC
